name: BingoSystem
version: ${project.version}
main: net.kigawa.plugin.kyosaba.system.bingosystem.BingoSystem
api-version: 1.16
authors: [ kigawa ]
commands:
  sendbingo:
    description: send to bingo
    usage: /sendbingo
    permission: bingosystem.game.startbingo
  startbingo:
    description: start bingo
    usage: /startbingo <name>
    permission: bingosystem.game.start
  GameCreate:
    description: create somethings
    usage: /bingosystem <subcommand>