name: BingoSystem
version: ${project.version}
main: net.kigawa.plugin.kyosaba.system.bingosystem.BingoSystem
api-version: 1.16
authors: [ kigawa ]
softdepend: [KigawaUtilLib]
commands:
  sendbingo:
    description: send to bingo
    usage: /sendbingo
    permission: bingosystem.sendbingo
  startbingo:
    description: start bingo
    usage: /startbingo <name>
    permission: bingosystem.startbingo
  bingosystem:
    description: create some things
    usage: /bingosystem <subcommand>
    permission: bingosystem.bingosystem