name: BingoSystem
version: ${project.version}
main: net.kigawa.plugin.kyosaba.system.bingosystem.BingoSystem
api-version: 1.16
authors: [ kigawa ]
commands:
  startbingo:
    description: start bingo
    usage: /<command>
    permission: bingosystem.game.startbingo
